class Constants {
  // ThingSpeak URLs
  static const String nitrogenUrl =
      'https://thingspeak.mathworks.com/channels/2599948/charts/1?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=10&title=Nitrogen%28N%29&type=line&yaxis=mg%2Fkg';
  static const String phosphorusUrl =
      'https://thingspeak.mathworks.com/channels/2599948/charts/2?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Phosphorus%28P%29&type=line&update=15&yaxis=mg%2Fkg';
  static const String potassiumUrl =
      'https://thingspeak.mathworks.com/channels/2599948/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Potassium&type=line&update=15&yaxis=mg%2Fkg';
}

// List of crops
const List<String> cropList = [
  'Wheat',
  'Rice',
  'Maize',
  'Barley',
  'Soybean',
  'Sugarcane',
  'Cotton',
  'Potato',
  'Tomato',
  'Onion',
  'Garlic',
  'Peas',
  'Lentils',
  'Mustard',
  'Chickpeas',
  'Sunflower',
  'Millet',
  'Sorghum',
  'Carrot',
  'Radish',
  'Cabbage',
  'Cauliflower',
  'Spinach',
  'Broccoli',
  'Cucumber',
  'Pumpkin',
  'Watermelon',
  'Melon',
  'Apple',
  'Banana',
  'Orange',
  'Mango',
  'Pineapple',
  'Papaya',
  'Guava',
  'Grapes',
  'Strawberry',
  'Blueberry',
  'Blackberry',
  'Pear',
  'Peach',
  'Cherry',
  'Plum',
  'Lychee',
  'Pomegranate',
  'Kiwi',
  'Apricot',
  'Almond',
  'Cashew',
  'Walnut',
  'Pistachio',
  'Peanut',
  'Coconut',
  'Tea',
  'Coffee',
  'Tobacco',
  'Rubber',
  'Jute',
  'Silk',
  'Cottonseed',
  'Linseed',
  'Castor',
  'Sesame',
  'Safflower',
  'Groundnut',
  'Beetroot',
  'Sweet Potato',
  'Turnip',
  'Sugarbeet',
  'Bamboo',
  'Vanilla',
  'Pepper',
  'Clove',
  'Cinnamon',
  'Nutmeg',
  'Cardamom',
  'Ginger',
  'Turmeric',
  'Fennel',
  'Coriander',
  'Mint',
  'Basil',
  'Rosemary',
  'Thyme',
  'Parsley',
  'Oregano',
  'Lavender',
  'Chili',
  'Bell Pepper',
  'Okra',
  'Zucchini',
  'Eggplant',
  'Asparagus',
  'Artichoke',
  'Leek',
  'Celery',
];

